# Generated by Django 5.1.7 on 2025-03-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'managed': False},
        ),
    ]
