# Generated by Django 5.1.7 on 2025-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
