# Generated by Django 5.1.7 on 2025-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users_avatars/default.png', upload_to='users_avatars/'),
        ),
    ]
